' Generated by bmxlocale from the canonical English catalogue.
' Do not edit this file directly.

SuperStrict

Import BlitzMax.Locale

Const BMK_MSG_COMMAND_UNKNOWN_OPERATION:Int = 1
Const BMK_MSG_COMMAND_ERROR_HEADING:Int = 2
Const BMK_MSG_APPLICATION_SOURCE_TYPE_UNRECOGNIZED:Int = 22
Const BMK_MSG_APPLICATION_SOURCE_FILE_OPEN_FAILED:Int = 23
Const BMK_MSG_APPLICATION_DIRECTORY_CREATION_FAILED:Int = 24
Const BMK_MSG_APPLICATION_RESOURCES_DIRECTORY_CREATION_FAILED:Int = 25
Const BMK_MSG_APPLICATION_OUTPUT_DIRECTORY_CREATION_FAILED:Int = 26
Const BMK_MSG_APPLICATION_OUTPUT_DIRECTORY_INVALID:Int = 27
Const BMK_MSG_APPLICATION_INFO_PLIST_CREATION_FAILED:Int = 28
Const BMK_MSG_APPLICATION_ICONS_CREATION_FAILED:Int = 29
Const BMK_MSG_ARCHIVE_OUTPUT_FILE_OPEN_FAILED:Int = 30
Const BMK_MSG_ARCHIVE_INPUT_FILE_OPEN_FAILED:Int = 31
Const BMK_MSG_BOOTSTRAP_FOLDER_CLEAR_FAILED:Int = 32
Const BMK_MSG_BOOTSTRAP_FOLDER_CREATION_FAILED:Int = 33
Const BMK_MSG_BOOTSTRAP_SUBDIRECTORY_CREATION_FAILED:Int = 34
Const BMK_MSG_APPLICATION_NAMED_APP_NOT_FOUND:Int = 35
Const BMK_MSG_COMMAND_NOT_ENOUGH_PARAMETERS:Int = 3
Const BMK_MSG_COMMAND_CLEAN_ONLY_MAKEAPP:Int = 4
Const BMK_MSG_COMMAND_MAKELIB_UNSUPPORTED_BY_BCC2:Int = 5
Const BMK_MSG_COMMAND_STANDALONE_MAKEMODS_UNAVAILABLE:Int = 6
Const BMK_MSG_COMMAND_MAKEMODS_TOO_MANY_ARGUMENTS:Int = 7
Const BMK_MSG_COMMAND_CLEANMODS_TOO_MANY_ARGUMENTS:Int = 8
Const BMK_MSG_COMMAND_EXECUTE_REQUIRES_ARGUMENT:Int = 9
Const BMK_MSG_COMMAND_COMPILE_ARGUMENT_COUNT:Int = 10
Const BMK_MSG_COMMAND_MAKEAPP_ARGUMENT_COUNT:Int = 11
Const BMK_MSG_COMMAND_MODULE_NAME_AND_OUTPUT_REQUIRED:Int = 12
Const BMK_MSG_COMMAND_UNZAPMOD_ARGUMENT_COUNT:Int = 13
Const BMK_MSG_COMMAND_RANLIBDIR_ARGUMENT_COUNT:Int = 14
Const BMK_MSG_OPTION_MISSING_ARGUMENT:Int = 15
Const BMK_MSG_OPTION_INVALID:Int = 16
Const BMK_MSG_TARGET_ARCHITECTURE_INVALID:Int = 17
Const BMK_MSG_TARGET_PLATFORM_INVALID:Int = 18
Const BMK_MSG_OPTION_HEAP_REQUIRES_PICO:Int = 19
Const BMK_MSG_OPTION_STORAGE_REQUIRES_PICO:Int = 20
Const BMK_MSG_TARGET_UNIVERSAL_MACOS_REQUIRES_XCODE_12:Int = 21
Const BMK_MSG_COMPILER_DECLARED_OUTPUT_MISSING:Int = 36
Const BMK_MSG_COMPILER_STAGING_CLEANUP_FAILED:Int = 37
Const BMK_MSG_TOOLCHAIN_DIRECTORY_NOT_FOUND:Int = 38
Const BMK_MSG_TOOLCHAIN_GCC_NOT_FOUND:Int = 39
Const BMK_MSG_TOOLCHAIN_GPP_NOT_FOUND:Int = 40
Const BMK_MSG_TOOLCHAIN_ARCHIVER_NOT_FOUND:Int = 41
Const BMK_MSG_TOOLCHAIN_PLATFORM_DIRECTORY_NOT_FOUND:Int = 42
Const BMK_MSG_ANDROID_SDK_TARGET_NOT_DETERMINED:Int = 43
Const BMK_MSG_ANDROID_SDK_TARGET_DIRECTORY_NOT_DETERMINED:Int = 44
Const BMK_MSG_ANDROID_HOME_NOT_SET:Int = 45
Const BMK_MSG_ANDROID_SDK_NOT_SET:Int = 46
Const BMK_MSG_ANDROID_NDK_NOT_SET:Int = 47
Const BMK_MSG_ANDROID_TOOLCHAIN_VERSION_NOT_SET:Int = 48
Const BMK_MSG_ANDROID_PLATFORM_NOT_SET:Int = 49
Const BMK_MSG_ANDROID_ANT_NOT_SET:Int = 50
Const BMK_MSG_NX_TOOLCHAIN_DIRECTORY_NOT_FOUND:Int = 51
Const BMK_MSG_NX_DEVKITPRO_NOT_SET:Int = 52
Const BMK_MSG_FRAMEWORK_ALREADY_SPECIFIED:Int = 53
Const BMK_MSG_CLEAN_APPLICATION_BUILD_DIRECTORY_UNEXPECTED:Int = 54
Const BMK_MSG_CLEAN_OUTPUT_INSIDE_APPLICATION_CACHE:Int = 55
Const BMK_MSG_COMPILER_EXECUTABLE_NOT_FOUND:Int = 56
Const BMK_MSG_BUILD_TEMPORARY_DIRECTORY_CREATION_FAILED:Int = 57
Const BMK_MSG_BUILD_UNEXPECTED_MODULE_LINK:Int = 58
Const BMK_MSG_ANDROID_APK_CREATION_FAILED:Int = 59
Const BMK_MSG_SPECIALIZATION_LINK_SOURCE_UNDECLARED:Int = 60
Const BMK_MSG_SPECIALIZATION_CACHE_PATH_IDENTITY_CONFLICT:Int = 61
Const BMK_MSG_SPECIALIZATION_GENERATED_IMPLEMENTATION_CONFLICT:Int = 62
Const BMK_MSG_SPECIALIZATION_OWNER_OBJECT_UNAVAILABLE:Int = 63
Const BMK_MSG_SOURCE_QUOTED_OWNERSHIP_IDENTITY_MISSING:Int = 64
Const BMK_MSG_SOURCE_QUOTED_MODULE_OWNER_CONFLICT:Int = 65
Const BMK_MSG_SOURCE_QUOTED_ESCAPES_ROOT:Int = 66
Const BMK_MSG_SOURCE_QUOTED_UNIT_PATH_CONFLICT:Int = 67
Const BMK_MSG_MODULE_DECLARATION_MISMATCH:Int = 68
Const BMK_MSG_BUILD_LINK_NOT_FOUND:Int = 69
Const BMK_MSG_COMPILER_STAGING_CONTEXT_MISSING:Int = 70
Const BMK_MSG_COMPILER_STAGING_PATH_EXISTS:Int = 71
Const BMK_MSG_COMPILER_STAGING_DIRECTORY_CREATION_FAILED:Int = 72
Const BMK_MSG_COMPILER_WORK_RESULT_MISSING:Int = 73
Const BMK_MSG_COMPILER_RESPONSE_MISSING:Int = 74
Const BMK_MSG_COMPILER_BUILD_BUNDLE_MISSING:Int = 75
Const BMK_MSG_COMPILER_STAGED_MANIFEST_MISSING:Int = 76
Const BMK_MSG_COMPILER_STAGED_OUTPUT_CONFLICT:Int = 77
Const BMK_MSG_COMPILER_OUTPUT_DIGEST_MISMATCH:Int = 78
Const BMK_MSG_COMPILER_OUTPUT_DIRECTORY_CREATION_FAILED:Int = 79
Const BMK_MSG_COMPILER_STAGED_OUTPUT_PUBLISH_FAILED:Int = 80
Const BMK_MSG_COMPILER_STAGED_MANIFEST_PUBLISH_FAILED:Int = 81
Const BMK_MSG_COMPILER_UNSAFE_STAGING_CLEANUP_REFUSED:Int = 82
Const BMK_MSG_COMPILER_FRESHNESS_STAMP_WRITE_FAILED:Int = 83
Const BMK_MSG_SPECIALIZATION_COMPILE_REQUEST_CONFLICT:Int = 84
Const BMK_MSG_SPECIALIZATION_OBJECT_DIRECTORY_CREATION_FAILED:Int = 85
Const BMK_MSG_SPECIALIZATION_OBJECT_MISSING:Int = 86
Const BMK_MSG_SPECIALIZATION_CACHE_KEY_WRITE_FAILED:Int = 87
Const BMK_MSG_INCBIN_RESOURCE_NOT_FOUND:Int = 88
Const BMK_MSG_INCBIN_OUTPUT_DIRECTORY_CREATION_FAILED:Int = 89
Const BMK_MSG_INCBIN_PACKAGING_UNIT_WRITE_FAILED:Int = 90
Const BMK_MSG_GRAPH_DEPENDENCY_MISSING:Int = 91
Const BMK_MSG_GRAPH_CIRCULAR_DEPENDENCY:Int = 92
Const BMK_MSG_INTERFACE_COMPATIBILITY_COPY_PUBLISH_FAILED:Int = 93
Const BMK_MSG_ARCHIVE_RESPONSE_FILE_WRITE_FAILED:Int = 94
Const BMK_MSG_ARCHIVE_CREATION_FAILED:Int = 95
Const BMK_MSG_ARCHIVE_PUBLISH_FAILED:Int = 96
Const BMK_MSG_PICO_SOURCE_NATIVE_DISCOVERY_READ_FAILED:Int = 97
Const BMK_MSG_PICO_HEADER_DIRECTORY_READ_FAILED:Int = 98
Const BMK_MSG_PICO_HEADER_READ_FAILED:Int = 99
Const BMK_MSG_PICO_SOURCE_NATIVE_OPTIONS_CONFLICT:Int = 100
Const BMK_MSG_PICO_QUOTED_SOURCE_READ_FAILED:Int = 101
Const BMK_MSG_PICO_NATIVE_SOURCE_OPTIONS_CONFLICT:Int = 102
Const BMK_MSG_PICO_PIO_SOURCE_READ_FAILED:Int = 103
Const BMK_MSG_PICO_PIO_PROGRAM_NAME_INVALID:Int = 104
Const BMK_MSG_PICO_PIO_PROGRAM_NAME_DUPLICATE:Int = 105
Const BMK_MSG_PICO_PIO_PROGRAM_MISSING:Int = 106
Const BMK_MSG_PICO_PIO_DISCOVERY_SOURCE_READ_FAILED:Int = 107
Const BMK_MSG_PICO_PIO_PROGRAM_OWNER_CONFLICT:Int = 108
Const BMK_MSG_PICO_MODULE_SOURCE_UNIT_READ_FAILED:Int = 109
Const BMK_MSG_PICO_MODULE_DECLARATION_MISMATCH:Int = 110
Const BMK_MSG_PICO_MODULE_QUOTED_SOURCE_ESCAPES_ROOT:Int = 111
Const BMK_MSG_PICO_APPLICATION_SOURCE_READ_FAILED:Int = 112
Const BMK_MSG_PICO_APPLICATION_QUOTED_SOURCE_READ_FAILED:Int = 113
Const BMK_MSG_PICO_APPLICATION_QUOTED_SOURCE_ESCAPES_ROOT:Int = 114
Const BMK_MSG_PICO_PATH_CONFIGURED_NOT_DIRECTORY:Int = 115
Const BMK_MSG_PICO_PATH_DIRECTORY_NOT_FOUND:Int = 116
Const BMK_MSG_PICO_PATH_CONFIGURED_EXECUTABLE_MISSING:Int = 117
Const BMK_MSG_PICO_PATH_ENVIRONMENT_EXECUTABLE_MISSING:Int = 118
Const BMK_MSG_PICO_PATH_EXECUTABLE_NOT_FOUND:Int = 119
Const BMK_MSG_PICO_BOARD_REQUIRED:Int = 120
Const BMK_MSG_PICO_BOARD_INVALID:Int = 121
Const BMK_MSG_PICO_HEAP_INVALID:Int = 122
Const BMK_MSG_PICO_HEAP_MINIMUM:Int = 123
Const BMK_MSG_PICO_STORAGE_INVALID:Int = 124
Const BMK_MSG_PICO_STORAGE_MINIMUM:Int = 125
Const BMK_MSG_PICO_STORAGE_SECTOR_ALIGNMENT:Int = 126
Const BMK_MSG_PICO_SDK_TARGET_CONFIGURATION_READ_FAILED:Int = 127
Const BMK_MSG_PICO_SDK_TARGET_KEY_MISSING:Int = 128
Const BMK_MSG_PICO_SDK_TARGET_KEY_EMPTY:Int = 129
Const BMK_MSG_PICO_SDK_TARGET_KEY_INVALID:Int = 130
Const BMK_MSG_PICO_UPLOAD_FAILED:Int = 131
Const BMK_MSG_PICO_COMMAND_FAILED:Int = 132
Const BMK_MSG_PICO_COMPILER_GENERATED_C_MISSING:Int = 133
Const BMK_MSG_PICO_COMPILER_INTERFACE_PUBLISH_FAILED:Int = 134
Const BMK_MSG_PICO_COMPILER_INTERFACE_MISSING:Int = 135
Const BMK_MSG_PICO_COMPILER_RUNTIME_HEADER_PUBLISH_FAILED:Int = 136
Const BMK_MSG_PICO_COMPILER_RUNTIME_HEADER_MISSING:Int = 137
Const BMK_MSG_PICO_INCBIN_SOURCE_READ_FAILED:Int = 138
Const BMK_MSG_PICO_INCBIN_PACKAGING_UNIT_WRITE_FAILED:Int = 139
Const BMK_MSG_PICO_SPECIALIZATION_SOURCE_MISSING:Int = 140
Const BMK_MSG_PICO_SPECIALIZATION_OWNER_CONFLICT:Int = 141
Const BMK_MSG_PICO_NATIVE_GRAPH_WRITE_FAILED:Int = 142
Const BMK_MSG_PICO_PIO_REGISTRY_WRITE_FAILED:Int = 143
Const BMK_MSG_PICO_PIO_CMAKE_WRITE_FAILED:Int = 144
Const BMK_MSG_PICO_TARGET_COMPILE_UNSUPPORTED:Int = 145
Const BMK_MSG_PICO_TARGET_ARM_REQUIRED:Int = 146
Const BMK_MSG_PICO_TARGET_BCC2_REQUIRED:Int = 147
Const BMK_MSG_PICO_TARGET_BUILD_MODE_REQUIRED:Int = 148
Const BMK_MSG_PICO_TARGET_MODULES_NOT_FOUND:Int = 149
Const BMK_MSG_PICO_TARGET_COMPILER_NOT_FOUND:Int = 150
Const BMK_MSG_PICO_TARGET_CMAKE_TEMPLATE_MISSING:Int = 151
Const BMK_MSG_PICO_TOOLCHAIN_CONFIGURED_GCC_MISSING:Int = 152
Const BMK_MSG_PICO_TOOLCHAIN_NOT_FOUND:Int = 153
Const BMK_MSG_PICO_OUTPUT_DIRECTORY_CREATION_FAILED:Int = 154
Const BMK_MSG_PICO_OUTPUT_PUBLISH_FAILED:Int = 155
Const BMK_MSG_PICO_PATH_CONFIGURED_PIOASM_MISSING:Int = 156
Const BMK_MSG_ARCHIVE_MERGE_FAILED:Int = 157
Const BMK_MSG_ARCHIVE_MERGED_PUBLISH_FAILED:Int = 158
Const BMK_MSG_LINKER_LINK_FAILED:Int = 159
Const BMK_MSG_LINKER_OUTPUT_PUBLISH_FAILED:Int = 160
Const BMK_MSG_APPLICATION_MERGE_FAILED:Int = 161
Const BMK_MSG_ANDROID_RESOURCES_MISSING:Int = 162
Const BMK_MSG_ANDROID_PROJECT_DIRECTORY_CREATION_FAILED:Int = 163
Const BMK_MSG_ANDROID_ASSETS_DIRECTORY_CREATION_FAILED:Int = 164
Const BMK_MSG_ANDROID_LIBS_DIRECTORY_CREATION_FAILED:Int = 165
Const BMK_MSG_ANDROID_ABI_DIRECTORY_CREATION_FAILED:Int = 166
Const BMK_MSG_ANDROID_STLPORT_COPY_FAILED:Int = 167
Const BMK_MSG_ANDROID_PACKAGE_CREATION_FAILED:Int = 168
Const BMK_MSG_ANDROID_CLASS_FILE_CREATION_FAILED:Int = 169
Const BMK_MSG_ANDROID_ARCHITECTURE_INVALID:Int = 170
Const BMK_MSG_NX_TOOL_MISSING:Int = 171
Const BMK_MSG_NX_DEFAULT_ICON_MISSING:Int = 172
Const BMK_MSG_TARGET_PROJECT_BLOCK_BEGIN_MISSING:Int = 173
Const BMK_MSG_TARGET_PROJECT_BLOCK_END_MISSING:Int = 174
Const BMK_MSG_IOS_TEMPLATE_DIRECTORY_MISSING:Int = 175
Const BMK_MSG_BOOTSTRAP_ASSET_DIRECTORY_MISSING:Int = 176
Const BMK_MSG_BOOTSTRAP_ASSET_NOT_DIRECTORY:Int = 177
Const BMK_MSG_BOOTSTRAP_ASSET_DESTINATION_CREATION_FAILED:Int = 178
Const BMK_MSG_BOOTSTRAP_SOURCE_DIRECTORY_MISSING:Int = 179
Const BMK_MSG_BOOTSTRAP_DIRECTORY_CREATION_FAILED:Int = 180
Const BMK_MSG_BOOTSTRAP_SOURCE_MISSING:Int = 181
Const BMK_MSG_BOOTSTRAP_LINKER_SCRIPT_MISSING:Int = 182
Const BMK_MSG_BOOTSTRAP_BUILD_SCRIPT_MISSING:Int = 183
Const BMK_MSG_BOOTSTRAP_CONFIGURATION_MISSING:Int = 184
Const BMK_MSG_BOOTSTRAP_CONFIGURATION_LOAD_FAILED:Int = 185
Const BMK_MSG_SPECIALIZATION_FILE_LINK_IDENTITY_MISMATCH:Int = 186
Const BMK_MSG_SPECIALIZATION_LINK_RECORD_CARDINALITY:Int = 187
Const BMK_MSG_COMPILER_MANIFEST_VERSION_UNSUPPORTED:Int = 188
Const BMK_MSG_COMPILER_MANIFEST_FILE_RECORD_MALFORMED:Int = 189
Const BMK_MSG_COMPILER_MANIFEST_UNSAFE_FILE_PATH:Int = 190
Const BMK_MSG_COMPILER_MANIFEST_DUPLICATE_FILE_PATH:Int = 191
Const BMK_MSG_COMPILER_MANIFEST_LINK_IDENTITY_MALFORMED:Int = 192
Const BMK_MSG_COMPILER_MANIFEST_UNSAFE_LINK_PATH:Int = 193
Const BMK_MSG_COMPILER_MANIFEST_DUPLICATE_LINK_INPUT:Int = 194
Const BMK_MSG_COMPILER_MANIFEST_RECORD_MALFORMED:Int = 195
Const BMK_MSG_COMPILER_MANIFEST_MISSING:Int = 196
Const BMK_MSG_COMPILER_MANIFEST_ENCODED_FIELD_MALFORMED:Int = 197
Const BMK_MSG_COMPILER_MANIFEST_UNSAFE_PATH_RESOLUTION:Int = 198
Const BMK_MSG_COMPILER_OUTPUT_HASH_FAILED:Int = 199
Const BMK_MSG_CLEAN_GENERATED_FILE_REMOVAL_FAILED:Int = 200
Const BMK_MSG_CLEAN_GENERATED_DIRECTORY_REMOVAL_FAILED:Int = 201
Const BMK_MSG_CLEAN_SYMBOLIC_OUTPUT_FILE_REFUSED:Int = 202
Const BMK_MSG_CLEAN_CACHE_ENTRY_OUTSIDE_DIRECTORY:Int = 203
Const BMK_MSG_CLEAN_UNEXPECTED_CACHE_DIRECTORY:Int = 204
Const BMK_MSG_CLEAN_SYMBOLIC_CACHE_DIRECTORY_REFUSED:Int = 205
Const BMK_MSG_CLEAN_CACHE_PATH_NOT_DIRECTORY:Int = 206
Const BMK_MSG_CLEAN_SYMBOLIC_LINK_INSIDE_CACHE_REFUSED:Int = 207
Const BMK_MSG_CLEAN_UNSUPPORTED_CACHE_ENTRY:Int = 208
Const BMK_MSG_CLEAN_UNSUPPORTED_OUTPUT:Int = 209
Const BMK_MSG_BCC2_ENGINE_START_FAILED:Int = 210
Const BMK_MSG_BCC2_ENGINE_HANDSHAKE_INCOMPATIBLE:Int = 211
Const BMK_MSG_BCC2_ENGINE_NOT_RUNNING:Int = 212
Const BMK_MSG_BCC2_ENGINE_RESULT_HEADER_MALFORMED:Int = 213
Const BMK_MSG_BCC2_ENGINE_RESULT_LENGTH_MALFORMED:Int = 214
Const BMK_MSG_BCC2_ENGINE_RESULT_BODY_MALFORMED:Int = 215
Const BMK_MSG_BCC2_ENGINE_RESULT_BODY_INCOMPLETE:Int = 216
Const BMK_MSG_BCC2_ENGINE_CACHE_INVALIDATION_NOT_RUNNING:Int = 217
Const BMK_MSG_BCC2_ENGINE_CACHE_INVALIDATION_REJECTED:Int = 218
Const BMK_MSG_BCC2_ENGINE_EXITED_UNEXPECTEDLY:Int = 219
Const BMK_MSG_CONFIG_REQUIRED_LOAD_FAILED:Int = 220
Const BMK_MSG_TOOLCHAIN_GCC_PROCESS_NOT_FOUND:Int = 221
Const BMK_MSG_TOOLCHAIN_XCODEBUILD_NOT_FOUND:Int = 222
Const BMK_MSG_MINGW_DLL_CRT_PATH_MISSING:Int = 223
Const BMK_MSG_MINGW_CRT_PATH_MISSING:Int = 224
Const BMK_MSG_MINGW_CRT_PATHS_MISSING:Int = 225
Const BMK_MSG_BUILD_OUTPUT_PUBLISH_FAILED:Int = 226
Const BMK_MSG_OPTIONS_EXPRESSION_CLOSING_PARENTHESIS_EXPECTED:Int = 227
Const BMK_MSG_OPTIONS_EXPRESSION_CLOSING_PARENTHESIS_UNEXPECTED:Int = 228
Const BMK_MSG_OPTIONS_EXPRESSION_CHARACTER_UNEXPECTED:Int = 229
Const BMK_MSG_OPTIONS_EXPRESSION_MISSING:Int = 230
Const BMK_MSG_MODULE_ARCHIVE_INTERFACE_MISSING:Int = 231
Const BMK_MSG_MODULE_ARCHIVE_PUBLISH_FAILED:Int = 232
Const BMK_MSG_MODULE_ARCHIVE_DIRECTORY_CREATION_FAILED:Int = 233
Const BMK_MSG_CONVERSION_FILENAME_REQUIRED:Int = 234
Const BMK_MSG_CONVERSION_SOURCE_OPEN_FAILED:Int = 235
Const BMK_MSG_CONVERSION_INCLUDED_SOURCE_OPEN_FAILED:Int = 236
Const BMK_MSG_MODULE_AMBIGUOUS:Int = 237
Const BMK_MSG_TARGET_PLATFORM_ARCHITECTURE_INVALID:Int = 238
Const BMK_MSG_OPTION_HEAP_REGION_REQUIRES_PICO:Int = 239
Const BMK_MSG_PICO_HEAP_REGION_INVALID:Int = 240
Const BMK_MSG_PICO_HEAP_PSRAM_FIXED_SIZE_REQUIRED:Int = 241
Const BMK_MSG_PICO_HEAP_PSRAM_CAPACITY_EXCEEDED:Int = 242

Type TBmkMessages
	Function CommandUnknownOperation:TLocalisedMessage(operation:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_UNKNOWN_OPERATION, "Unknown operation '{operation}'", [TMessageArg.Create("operation", operation)])
	End Function
	Function CommandErrorHeading:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_ERROR_HEADING, "Command line error")
	End Function
	Function ApplicationSourceTypeUnrecognized:TLocalisedMessage(extension:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_SOURCE_TYPE_UNRECOGNIZED, "Unrecognized app source file type:{extension}", [TMessageArg.Create("extension", extension)])
	End Function
	Function ApplicationSourceFileOpenFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_SOURCE_FILE_OPEN_FAILED, "Unable to open source file '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function ApplicationDirectoryCreationFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_DIRECTORY_CREATION_FAILED, "Unable to create application directory")
	End Function
	Function ApplicationResourcesDirectoryCreationFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_RESOURCES_DIRECTORY_CREATION_FAILED, "Unable to create resources directory")
	End Function
	Function ApplicationOutputDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_OUTPUT_DIRECTORY_CREATION_FAILED, "Unable to create output directory : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ApplicationOutputDirectoryInvalid:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_OUTPUT_DIRECTORY_INVALID, "Invalid output directory : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ApplicationInfoPlistCreationFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_INFO_PLIST_CREATION_FAILED, "Unable to create Info.plist")
	End Function
	Function ApplicationIconsCreationFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_ICONS_CREATION_FAILED, "Unable to create icons")
	End Function
	Function ArchiveOutputFileOpenFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ARCHIVE_OUTPUT_FILE_OPEN_FAILED, "Unable to open output file")
	End Function
	Function ArchiveInputFileOpenFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ARCHIVE_INPUT_FILE_OPEN_FAILED, "Unable to open input file")
	End Function
	Function BootstrapFolderClearFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_FOLDER_CLEAR_FAILED, "Error clearing bootstrap folder")
	End Function
	Function BootstrapFolderCreationFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_FOLDER_CREATION_FAILED, "Error creating bootstrap folder")
	End Function
	Function BootstrapSubdirectoryCreationFailed:TLocalisedMessage(directory:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_SUBDIRECTORY_CREATION_FAILED, "Error creating bootstrap/{directory} folder", [TMessageArg.Create("directory", directory)])
	End Function
	Function ApplicationNamedAppNotFound:TLocalisedMessage(application:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_NAMED_APP_NOT_FOUND, "App not found : {application}", [TMessageArg.Create("application", application)])
	End Function
	Function CommandNotEnoughParameters:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_NOT_ENOUGH_PARAMETERS, "Not enough parameters")
	End Function
	Function CommandCleanOnlyMakeapp:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_CLEAN_ONLY_MAKEAPP, "The -clean option is available only for makeapp")
	End Function
	Function CommandMakelibUnsupportedByBcc2:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_MAKELIB_UNSUPPORTED_BY_BCC2, "makelib is not yet supported by canonical-only bcc2")
	End Function
	Function CommandStandaloneMakemodsUnavailable:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_STANDALONE_MAKEMODS_UNAVAILABLE, "Standalone build not available for makemods")
	End Function
	Function CommandMakemodsTooManyArguments:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_MAKEMODS_TOO_MANY_ARGUMENTS, "Expecting only 1 argument for makemods")
	End Function
	Function CommandCleanmodsTooManyArguments:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_CLEANMODS_TOO_MANY_ARGUMENTS, "Expecting only 1 argument for cleanmods")
	End Function
	Function CommandExecuteRequiresArgument:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_EXECUTE_REQUIRES_ARGUMENT, "Execute requires at least 1 argument")
	End Function
	Function CommandCompileArgumentCount:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_COMPILE_ARGUMENT_COUNT, "Expecting only 1 argument for compile")
	End Function
	Function CommandMakeappArgumentCount:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_MAKEAPP_ARGUMENT_COUNT, "Expecting only 1 argument for makeapp")
	End Function
	Function CommandModuleNameAndOutputRequired:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_MODULE_NAME_AND_OUTPUT_REQUIRED, "Both module name and outfile required")
	End Function
	Function CommandUnzapmodArgumentCount:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_UNZAPMOD_ARGUMENT_COUNT, "Expecting 1 argument for unzapmod")
	End Function
	Function CommandRanlibdirArgumentCount:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMMAND_RANLIBDIR_ARGUMENT_COUNT, "Expecting 1 argument for ranlibdir")
	End Function
	Function OptionMissingArgument:TLocalisedMessage(option:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTION_MISSING_ARGUMENT, "Missing arg for '-{option}'", [TMessageArg.Create("option", option)])
	End Function
	Function OptionInvalid:TLocalisedMessage(option:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTION_INVALID, "Invalid option '{option}'", [TMessageArg.Create("option", option)])
	End Function
	Function TargetArchitectureInvalid:TLocalisedMessage(architecture:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TARGET_ARCHITECTURE_INVALID, "Not a valid architecture : '{architecture}'", [TMessageArg.Create("architecture", architecture)])
	End Function
	Function TargetPlatformInvalid:TLocalisedMessage(platform:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TARGET_PLATFORM_INVALID, "Not valid platform : '{platform}'", [TMessageArg.Create("platform", platform)])
	End Function
	Function OptionHeapRequiresPico:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTION_HEAP_REQUIRES_PICO, "-heap is currently supported only by the pico target")
	End Function
	Function OptionStorageRequiresPico:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTION_STORAGE_REQUIRES_PICO, "-storage is currently supported only by the pico target")
	End Function
	Function TargetUniversalMacosRequiresXcode12:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TARGET_UNIVERSAL_MACOS_REQUIRES_XCODE_12, "XCode 12+ required for universal macOS build")
	End Function
	Function CompilerDeclaredOutputMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_DECLARED_OUTPUT_MISSING, "BMKGEN020 declared compiler output is missing: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerStagingCleanupFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_STAGING_CLEANUP_FAILED, "BMKGEN054 unable to remove compiler staging directory: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ToolchainDirectoryNotFound:TLocalisedMessage(native:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TOOLCHAIN_DIRECTORY_NOT_FOUND, "Cannot determine toolchain dir for '{native}', at '{path}'", [TMessageArg.Create("native", native), TMessageArg.Create("path", path)])
	End Function
	Function ToolchainGccNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TOOLCHAIN_GCC_NOT_FOUND, "gcc not found at '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function ToolchainGppNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TOOLCHAIN_GPP_NOT_FOUND, "g++ not found at '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function ToolchainArchiverNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TOOLCHAIN_ARCHIVER_NOT_FOUND, "ar not found at '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function ToolchainPlatformDirectoryNotFound:TLocalisedMessage(architecture:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TOOLCHAIN_PLATFORM_DIRECTORY_NOT_FOUND, "Cannot determine platform dir for '{architecture}' at '{path}'", [TMessageArg.Create("architecture", architecture), TMessageArg.Create("path", path)])
	End Function
	Function AndroidSdkTargetNotDetermined:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_SDK_TARGET_NOT_DETERMINED, "Cannot determine SDK target for '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidSdkTargetDirectoryNotDetermined:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_SDK_TARGET_DIRECTORY_NOT_DETERMINED, "Cannot determine SDK target dir. ANDROID_SDK_TARGET or android.sdk.target option is not set, and auto-lookup failed.")
	End Function
	Function AndroidHomeNotSet:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_HOME_NOT_SET, "ANDROID_HOME or 'android.home' config option not set")
	End Function
	Function AndroidSdkNotSet:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_SDK_NOT_SET, "ANDROID_SDK or 'android.sdk' config option not set")
	End Function
	Function AndroidNdkNotSet:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_NDK_NOT_SET, "ANDROID_NDK or 'android.ndk' config option not set")
	End Function
	Function AndroidToolchainVersionNotSet:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_TOOLCHAIN_VERSION_NOT_SET, "ANDROID_TOOLCHAIN_VERSION or 'android.toolchain.version' config option not set")
	End Function
	Function AndroidPlatformNotSet:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_PLATFORM_NOT_SET, "ANDROID_PLATFORM or 'android.platform' config option not set")
	End Function
	Function AndroidAntNotSet:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_ANT_NOT_SET, "ANT_HOME or 'ant.home' config option not set, and resources missing apache-ant.")
	End Function
	Function NxToolchainDirectoryNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_NX_TOOLCHAIN_DIRECTORY_NOT_FOUND, "Cannot determine toolchain dir for NX, at '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function NxDevkitproNotSet:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_NX_DEVKITPRO_NOT_SET, "DEVKITPRO or 'nx.devkitpro' config option not set")
	End Function
	Function FrameworkAlreadySpecified:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_FRAMEWORK_ALREADY_SPECIFIED, "Framework already specified on commandline")
	End Function
	Function CleanApplicationBuildDirectoryUnexpected:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_APPLICATION_BUILD_DIRECTORY_UNEXPECTED, "BMKCLEAN008 refusing unexpected application build directory: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CleanOutputInsideApplicationCache:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_OUTPUT_INSIDE_APPLICATION_CACHE, "BMKCLEAN009 refusing to clean an application cache containing the requested output: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerExecutableNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_EXECUTABLE_NOT_FOUND, "BMKGEN030 bcc compiler was not found: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BuildTemporaryDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BUILD_TEMPORARY_DIRECTORY_CREATION_FAILED, "Unable to create temporary directory : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BuildUnexpectedModuleLink:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BUILD_UNEXPECTED_MODULE_LINK, "Build Error: Did not expect to link against {path}", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidApkCreationFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_APK_CREATION_FAILED, "Error creating apk")
	End Function
	Function SpecializationLinkSourceUndeclared:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_LINK_SOURCE_UNDECLARED, "BMKGEN022 specialization link source is not declared: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SpecializationCachePathIdentityConflict:TLocalisedMessage(path:String, existingIdentity:String, requestedIdentity:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_CACHE_PATH_IDENTITY_CONFLICT, "BMKGEN055 specialization cache path is claimed by distinct identities: {path} ({existingIdentity} and {requestedIdentity})", [TMessageArg.Create("path", path), TMessageArg.Create("existingIdentity", existingIdentity), TMessageArg.Create("requestedIdentity", requestedIdentity)])
	End Function
	Function SpecializationGeneratedImplementationConflict:TLocalisedMessage(identity:String, cacheKey:String, existingManifest:String, existingDigest:String, candidateManifest:String, candidateDigest:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_GENERATED_IMPLEMENTATION_CONFLICT, "BMKGEN038 conflicting generated implementations for specialization {identity} (cache {cacheKey}; {existingManifest} -> {existingDigest}; {candidateManifest} -> {candidateDigest})", [TMessageArg.Create("identity", identity), TMessageArg.Create("cacheKey", cacheKey), TMessageArg.Create("existingManifest", existingManifest), TMessageArg.Create("existingDigest", existingDigest), TMessageArg.Create("candidateManifest", candidateManifest), TMessageArg.Create("candidateDigest", candidateDigest)])
	End Function
	Function SpecializationOwnerObjectUnavailable:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_OWNER_OBJECT_UNAVAILABLE, "BMKGEN039 selected specialization owner object is unavailable: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SourceQuotedOwnershipIdentityMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SOURCE_QUOTED_OWNERSHIP_IDENTITY_MISSING, "BMKGEN041 quoted BlitzMax source has no bcc2 ownership identity: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SourceQuotedModuleOwnerConflict:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SOURCE_QUOTED_MODULE_OWNER_CONFLICT, "BMKGEN040 quoted BlitzMax source has conflicting bcc2 module owners: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SourceQuotedEscapesRoot:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SOURCE_QUOTED_ESCAPES_ROOT, "BMKGEN048 quoted BlitzMax source escapes its bcc2 source root: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SourceQuotedUnitPathConflict:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SOURCE_QUOTED_UNIT_PATH_CONFLICT, "BMKGEN049 quoted BlitzMax source has conflicting bcc2 unit paths: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ModuleDeclarationMismatch:TLocalisedMessage(declaredName:String, expectedName:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_MODULE_DECLARATION_MISMATCH, "Module declaration '{declaredName}' does not match path-derived module name '{expectedName}' for '{path}'", [TMessageArg.Create("declaredName", declaredName), TMessageArg.Create("expectedName", expectedName), TMessageArg.Create("path", path)])
	End Function
	Function BuildLinkNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BUILD_LINK_NOT_FOUND, "Can't find link for : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerStagingContextMissing:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_STAGING_CONTEXT_MISSING, "BMKGEN050 cannot stage compiler output without a build root and manifest path")
	End Function
	Function CompilerStagingPathExists:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_STAGING_PATH_EXISTS, "BMKGEN050 compiler staging path already exists: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerStagingDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_STAGING_DIRECTORY_CREATION_FAILED, "BMKGEN050 unable to create compiler staging directory: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerWorkResultMissing:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_WORK_RESULT_MISSING, "BMKGEN049 missing bcc2 compiler work result")
	End Function
	Function CompilerResponseMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_RESPONSE_MISSING, "BMKGEN049 missing bcc2 compiler response for {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerBuildBundleMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_BUILD_BUNDLE_MISSING, "BMKGEN031 bcc failed to produce a build bundle for {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerStagedManifestMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_STAGED_MANIFEST_MISSING, "BMKGEN051 staged compiler manifest is missing: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerStagedOutputConflict:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_STAGED_OUTPUT_CONFLICT, "BMKGEN052 conflicting staged compiler outputs for {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerOutputDigestMismatch:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_OUTPUT_DIGEST_MISMATCH, "BMKGEN021 compiler output digest mismatch: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerOutputDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_OUTPUT_DIRECTORY_CREATION_FAILED, "BMKGEN053 unable to create compiler output directory: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerStagedOutputPublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_STAGED_OUTPUT_PUBLISH_FAILED, "BMKGEN053 unable to publish staged compiler output: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerStagedManifestPublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_STAGED_MANIFEST_PUBLISH_FAILED, "BMKGEN053 unable to publish staged compiler manifest: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerUnsafeStagingCleanupRefused:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_UNSAFE_STAGING_CLEANUP_REFUSED, "BMKGEN054 refusing unsafe compiler staging cleanup: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerFreshnessStampWriteFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_FRESHNESS_STAMP_WRITE_FAILED, "BMKGEN035 unable to write bcc2 generation freshness stamp: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SpecializationCompileRequestConflict:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_COMPILE_REQUEST_CONFLICT, "BMKGEN039 conflicting compile requests for specialization object: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SpecializationObjectDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_OBJECT_DIRECTORY_CREATION_FAILED, "BMKGEN032 unable to create specialization object directory: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SpecializationObjectMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_OBJECT_MISSING, "BMKGEN033 specialization compiler did not produce: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SpecializationCacheKeyWriteFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_CACHE_KEY_WRITE_FAILED, "BMKGEN034 unable to record specialization object cache key: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function IncbinResourceNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_INCBIN_RESOURCE_NOT_FOUND, "BMKGEN041 Incbin resource was not found: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function IncbinOutputDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_INCBIN_OUTPUT_DIRECTORY_CREATION_FAILED, "BMKGEN042 unable to create Incbin output directory: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function IncbinPackagingUnitWriteFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_INCBIN_PACKAGING_UNIT_WRITE_FAILED, "BMKGEN043 unable to write Incbin packaging unit: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function GraphDependencyMissing:TLocalisedMessage(dependency:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_GRAPH_DEPENDENCY_MISSING, "Build graph dependency is missing: {dependency}", [TMessageArg.Create("dependency", dependency)])
	End Function
	Function GraphCircularDependency:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_GRAPH_CIRCULAR_DEPENDENCY, "circular dependency!")
	End Function
	Function InterfaceCompatibilityCopyPublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_INTERFACE_COMPATIBILITY_COPY_PUBLISH_FAILED, "BMKGEN037 unable to publish bcc compatibility interface copy: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ArchiveResponseFileWriteFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ARCHIVE_RESPONSE_FILE_WRITE_FAILED, "Build Error: Failed to write archive response file {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ArchiveCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ARCHIVE_CREATION_FAILED, "Build Error: Failed to create archive {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ArchivePublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ARCHIVE_PUBLISH_FAILED, "Build Error: Failed to publish archive {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoSourceNativeDiscoveryReadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_SOURCE_NATIVE_DISCOVERY_READ_FAILED, "Unable to read Pico source while discovering native imports at {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoHeaderDirectoryReadFailed:TLocalisedMessage(imported_path:String, source_path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_HEADER_DIRECTORY_READ_FAILED, "Unable to read quoted Pico header directory '{imported_path}' from {source_path}", [TMessageArg.Create("imported_path", imported_path), TMessageArg.Create("source_path", source_path)])
	End Function
	Function PicoHeaderReadFailed:TLocalisedMessage(imported_path:String, source_path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_HEADER_READ_FAILED, "Unable to read quoted Pico header '{imported_path}' from {source_path}", [TMessageArg.Create("imported_path", imported_path), TMessageArg.Create("source_path", source_path)])
	End Function
	Function PicoSourceNativeOptionsConflict:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_SOURCE_NATIVE_OPTIONS_CONFLICT, "Quoted Pico source has conflicting native compiler options: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoQuotedSourceReadFailed:TLocalisedMessage(imported_path:String, source_path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_QUOTED_SOURCE_READ_FAILED, "Unable to read quoted Pico source '{imported_path}' from {source_path}", [TMessageArg.Create("imported_path", imported_path), TMessageArg.Create("source_path", source_path)])
	End Function
	Function PicoNativeSourceOptionsConflict:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_NATIVE_SOURCE_OPTIONS_CONFLICT, "Quoted Pico native source has conflicting compiler options: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoPioSourceReadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PIO_SOURCE_READ_FAILED, "Unable to read imported PIO source {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoPioProgramNameInvalid:TLocalisedMessage(name:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PIO_PROGRAM_NAME_INVALID, "Invalid PIO program name '{name}' in {path}", [TMessageArg.Create("name", name), TMessageArg.Create("path", path)])
	End Function
	Function PicoPioProgramNameDuplicate:TLocalisedMessage(name:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PIO_PROGRAM_NAME_DUPLICATE, "Duplicate PIO program name '{name}' in {path}", [TMessageArg.Create("name", name), TMessageArg.Create("path", path)])
	End Function
	Function PicoPioProgramMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PIO_PROGRAM_MISSING, "Imported PIO source declares no .program: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoPioDiscoverySourceReadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PIO_DISCOVERY_SOURCE_READ_FAILED, "Unable to read Pico source while discovering PIO imports at {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoPioProgramOwnerConflict:TLocalisedMessage(name:String, first_path:String, second_path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PIO_PROGRAM_OWNER_CONFLICT, "PIO program name '{name}' is declared by both {first_path} and {second_path}", [TMessageArg.Create("name", name), TMessageArg.Create("first_path", first_path), TMessageArg.Create("second_path", second_path)])
	End Function
	Function PicoModuleSourceUnitReadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_MODULE_SOURCE_UNIT_READ_FAILED, "Unable to read Pico source unit at {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoModuleDeclarationMismatch:TLocalisedMessage(path:String, declared_name:String, expected_name:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_MODULE_DECLARATION_MISMATCH, "Pico module source '{path}' declares '{declared_name}', expected '{expected_name}'", [TMessageArg.Create("path", path), TMessageArg.Create("declared_name", declared_name), TMessageArg.Create("expected_name", expected_name)])
	End Function
	Function PicoModuleQuotedSourceEscapesRoot:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_MODULE_QUOTED_SOURCE_ESCAPES_ROOT, "Quoted Pico source escapes module root: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoApplicationSourceReadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_APPLICATION_SOURCE_READ_FAILED, "Unable to read Pico application source at {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoApplicationQuotedSourceReadFailed:TLocalisedMessage(imported_path:String, source_path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_APPLICATION_QUOTED_SOURCE_READ_FAILED, "Unable to read quoted Pico application source '{imported_path}' from {source_path}", [TMessageArg.Create("imported_path", imported_path), TMessageArg.Create("source_path", source_path)])
	End Function
	Function PicoApplicationQuotedSourceEscapesRoot:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_APPLICATION_QUOTED_SOURCE_ESCAPES_ROOT, "Quoted Pico application source escapes its source root: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoPathConfiguredNotDirectory:TLocalisedMessage(label:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PATH_CONFIGURED_NOT_DIRECTORY, "The configured {label} path does not name a directory: {path}", [TMessageArg.Create("label", label), TMessageArg.Create("path", path)])
	End Function
	Function PicoPathDirectoryNotFound:TLocalisedMessage(label:String, option_key:String, environment_key:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PATH_DIRECTORY_NOT_FOUND, "Unable to locate {label}. Set #addoption {option_key} in custom.bmk or {environment_key}, or install it under the user Pico SDK directory.", [TMessageArg.Create("label", label), TMessageArg.Create("option_key", option_key), TMessageArg.Create("environment_key", environment_key)])
	End Function
	Function PicoPathConfiguredExecutableMissing:TLocalisedMessage(label:String, executable:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PATH_CONFIGURED_EXECUTABLE_MISSING, "The configured {label} path does not contain {executable}: {path}", [TMessageArg.Create("label", label), TMessageArg.Create("executable", executable), TMessageArg.Create("path", path)])
	End Function
	Function PicoPathEnvironmentExecutableMissing:TLocalisedMessage(environment_key:String, executable:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PATH_ENVIRONMENT_EXECUTABLE_MISSING, "The {environment_key} path does not contain {executable}: {path}", [TMessageArg.Create("environment_key", environment_key), TMessageArg.Create("executable", executable), TMessageArg.Create("path", path)])
	End Function
	Function PicoPathExecutableNotFound:TLocalisedMessage(label:String, option_key:String, environment_key:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PATH_EXECUTABLE_NOT_FOUND, "Unable to locate {label}. Set #addoption {option_key} in custom.bmk, set {environment_key}, add it to PATH, or install it under the user Pico SDK directory.", [TMessageArg.Create("label", label), TMessageArg.Create("option_key", option_key), TMessageArg.Create("environment_key", environment_key)])
	End Function
	Function PicoBoardRequired:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_BOARD_REQUIRED, "A Pico SDK board name is required")
	End Function
	Function PicoBoardInvalid:TLocalisedMessage(board:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_BOARD_INVALID, "Invalid Pico SDK board name '{board}'", [TMessageArg.Create("board", board)])
	End Function
	Function PicoHeapInvalid:TLocalisedMessage(value:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_HEAP_INVALID, "Invalid Pico heap size '{value}'", [TMessageArg.Create("value", value)])
	End Function
	Function PicoHeapMinimum:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_HEAP_MINIMUM, "Pico heap size must be at least 1 KiB")
	End Function
	Function PicoStorageInvalid:TLocalisedMessage(value:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_STORAGE_INVALID, "Invalid Pico storage size '{value}'", [TMessageArg.Create("value", value)])
	End Function
	Function PicoStorageMinimum:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_STORAGE_MINIMUM, "Pico storage must be at least 8 KiB")
	End Function
	Function PicoStorageSectorAlignment:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_STORAGE_SECTOR_ALIGNMENT, "Pico storage size must be a multiple of the 4096-byte flash sector size")
	End Function
	Function PicoSdkTargetConfigurationReadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_SDK_TARGET_CONFIGURATION_READ_FAILED, "Unable to read Pico SDK target configuration from {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoSdkTargetKeyMissing:TLocalisedMessage(key:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_SDK_TARGET_KEY_MISSING, "The Pico SDK did not publish {key} in {path}", [TMessageArg.Create("key", key), TMessageArg.Create("path", path)])
	End Function
	Function PicoSdkTargetKeyEmpty:TLocalisedMessage(key:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_SDK_TARGET_KEY_EMPTY, "The Pico SDK published an empty {key} value", [TMessageArg.Create("key", key)])
	End Function
	Function PicoSdkTargetKeyInvalid:TLocalisedMessage(key:String, value:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_SDK_TARGET_KEY_INVALID, "The Pico SDK published an invalid {key} value: {value}", [TMessageArg.Create("key", key), TMessageArg.Create("value", value)])
	End Function
	Function PicoUploadFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_UPLOAD_FAILED, "Uploading Pico firmware failed")
	End Function
	Function PicoCommandFailed:TLocalisedMessage(description:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_COMMAND_FAILED, "{description} failed", [TMessageArg.Create("description", description)])
	End Function
	Function PicoCompilerGeneratedCMissing:TLocalisedMessage(name:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_COMPILER_GENERATED_C_MISSING, "Pico compiler build bundle did not declare {name}", [TMessageArg.Create("name", name)])
	End Function
	Function PicoCompilerInterfacePublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_COMPILER_INTERFACE_PUBLISH_FAILED, "Unable to publish Pico compiler interface output {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoCompilerInterfaceMissing:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_COMPILER_INTERFACE_MISSING, "Pico compiler build bundle did not declare its module interface")
	End Function
	Function PicoCompilerRuntimeHeaderPublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_COMPILER_RUNTIME_HEADER_PUBLISH_FAILED, "Unable to publish Pico compiler runtime header {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoCompilerRuntimeHeaderMissing:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_COMPILER_RUNTIME_HEADER_MISSING, "Pico compiler build bundle did not declare its runtime header")
	End Function
	Function PicoIncbinSourceReadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_INCBIN_SOURCE_READ_FAILED, "Unable to read Pico Incbin source at {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoIncbinPackagingUnitWriteFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_INCBIN_PACKAGING_UNIT_WRITE_FAILED, "BMKGEN043 unable to write Pico Incbin packaging unit: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoSpecializationSourceMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_SPECIALIZATION_SOURCE_MISSING, "Pico generic specialization source is absent from its build manifest: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoSpecializationOwnerConflict:TLocalisedMessage(identity:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_SPECIALIZATION_OWNER_CONFLICT, "Conflicting Pico generic specialization owners for {identity}", [TMessageArg.Create("identity", identity)])
	End Function
	Function PicoNativeGraphWriteFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_NATIVE_GRAPH_WRITE_FAILED, "Unable to write generated Pico native source graph {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoPioRegistryWriteFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PIO_REGISTRY_WRITE_FAILED, "Unable to write generated Pico PIO registry {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoPioCmakeWriteFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PIO_CMAKE_WRITE_FAILED, "Unable to write generated Pico PIO CMake integration {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoTargetCompileUnsupported:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TARGET_COMPILE_UNSUPPORTED, "The pico target currently supports makeapp, not compile")
	End Function
	Function PicoTargetArmRequired:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TARGET_ARM_REQUIRED, "The pico target currently requires the arm architecture")
	End Function
	Function PicoTargetBcc2Required:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TARGET_BCC2_REQUIRED, "The pico target requires bcc2")
	End Function
	Function PicoTargetBuildModeRequired:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TARGET_BUILD_MODE_REQUIRED, "The pico target requires an explicit -r or -d build mode")
	End Function
	Function PicoTargetModulesNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TARGET_MODULES_NOT_FOUND, "Pico modules were not found at {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoTargetCompilerNotFound:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TARGET_COMPILER_NOT_FOUND, "Pico-enabled bcc2 was not found at {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoTargetCmakeTemplateMissing:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TARGET_CMAKE_TEMPLATE_MISSING, "Pico CMake application template was not found")
	End Function
	Function PicoToolchainConfiguredGccMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TOOLCHAIN_CONFIGURED_GCC_MISSING, "The configured Pico ARM toolchain does not contain arm-none-eabi-gcc: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoToolchainNotFound:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_TOOLCHAIN_NOT_FOUND, "Unable to locate the Pico ARM toolchain. Set #addoption pico.toolchain in custom.bmk, set PICO_TOOLCHAIN_PATH, add arm-none-eabi-gcc to PATH, or install it under the user Pico SDK directory.")
	End Function
	Function PicoOutputDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_OUTPUT_DIRECTORY_CREATION_FAILED, "Unable to create Pico output directory {path}", [TMessageArg.Create("path", path)])
	End Function
	Function PicoOutputPublishFailed:TLocalisedMessage(extension:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_OUTPUT_PUBLISH_FAILED, "Unable to publish {extension} output", [TMessageArg.Create("extension", extension)])
	End Function
	Function PicoPathConfiguredPioasmMissing:TLocalisedMessage(executable:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_PATH_CONFIGURED_PIOASM_MISSING, "The configured pioasm path does not contain {executable}: {path}", [TMessageArg.Create("executable", executable), TMessageArg.Create("path", path)])
	End Function
	Function ArchiveMergeFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ARCHIVE_MERGE_FAILED, "Build Error: Failed to merge archive {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ArchiveMergedPublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ARCHIVE_MERGED_PUBLISH_FAILED, "Build Error: Failed to publish merged archive {path}", [TMessageArg.Create("path", path)])
	End Function
	Function LinkerLinkFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_LINKER_LINK_FAILED, "Build Error: Failed to link {path}", [TMessageArg.Create("path", path)])
	End Function
	Function LinkerOutputPublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_LINKER_OUTPUT_PUBLISH_FAILED, "Build Error: Failed to publish linked output {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ApplicationMergeFailed:TLocalisedMessage(first_path:String, second_path:String, output_path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_APPLICATION_MERGE_FAILED, "Merge Error: Failed to merge {first_path} and {second_path} into {output_path}", [TMessageArg.Create("first_path", first_path), TMessageArg.Create("second_path", second_path), TMessageArg.Create("output_path", output_path)])
	End Function
	Function AndroidResourcesMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_RESOURCES_MISSING, "Missing resources folder for Android build : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidProjectDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_PROJECT_DIRECTORY_CREATION_FAILED, "Error creating project dir '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidAssetsDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_ASSETS_DIRECTORY_CREATION_FAILED, "Error creating assests dir '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidLibsDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_LIBS_DIRECTORY_CREATION_FAILED, "Error creating libs dir '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidAbiDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_ABI_DIRECTORY_CREATION_FAILED, "Error creating libs abi dir '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidStlportCopyFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_STLPORT_COPY_FAILED, "Error copying libstlport_shared.so from '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidPackageCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_PACKAGE_CREATION_FAILED, "Error creating package '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidClassFileCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_CLASS_FILE_CREATION_FAILED, "Error creating class file '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function AndroidArchitectureInvalid:TLocalisedMessage(architecture:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_ANDROID_ARCHITECTURE_INVALID, "Not a valid architecture '{architecture}'", [TMessageArg.Create("architecture", architecture)])
	End Function
	Function NxToolMissing:TLocalisedMessage(tool:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_NX_TOOL_MISSING, "{tool} tool not present at {path}", [TMessageArg.Create("tool", tool), TMessageArg.Create("path", path)])
	End Function
	Function NxDefaultIconMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_NX_DEFAULT_ICON_MISSING, "Default icon not found at {path}", [TMessageArg.Create("path", path)])
	End Function
	Function TargetProjectBlockBeginMissing:TLocalisedMessage(tag:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TARGET_PROJECT_BLOCK_BEGIN_MISSING, "Error updating target project - can't find block begin tag '{tag}'.", [TMessageArg.Create("tag", tag)])
	End Function
	Function TargetProjectBlockEndMissing:TLocalisedMessage(tag:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TARGET_PROJECT_BLOCK_END_MISSING, "Error updating target project - can't find block end tag '{tag}'.", [TMessageArg.Create("tag", tag)])
	End Function
	Function IosTemplateDirectoryMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_IOS_TEMPLATE_DIRECTORY_MISSING, "iOS template dir is missing. Expecting it at '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapAssetDirectoryMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_ASSET_DIRECTORY_MISSING, "Expected dir missing : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapAssetNotDirectory:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_ASSET_NOT_DIRECTORY, "Not a dir : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapAssetDestinationCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_ASSET_DESTINATION_CREATION_FAILED, "Error creating {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapSourceDirectoryMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_SOURCE_DIRECTORY_MISSING, "Source dir not found : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapDirectoryCreationFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_DIRECTORY_CREATION_FAILED, "Unable to create {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapSourceMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_SOURCE_MISSING, "Not found : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapLinkerScriptMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_LINKER_SCRIPT_MISSING, "ld script missing : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapBuildScriptMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_BUILD_SCRIPT_MISSING, "build script missing : {path}", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapConfigurationMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_CONFIGURATION_MISSING, "{path} not found; bmk2 requires its own bootstrap configuration", [TMessageArg.Create("path", path)])
	End Function
	Function BootstrapConfigurationLoadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BOOTSTRAP_CONFIGURATION_LOAD_FAILED, "Could not load {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SpecializationFileLinkIdentityMismatch:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_FILE_LINK_IDENTITY_MISMATCH, "BMKGEN023 specialization file/link identity mismatch: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function SpecializationLinkRecordCardinality:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_SPECIALIZATION_LINK_RECORD_CARDINALITY, "BMKGEN024 specialization C unit must have exactly one link record: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerManifestVersionUnsupported:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_VERSION_UNSUPPORTED, "BMKGEN001 unsupported or missing compiler build manifest version")
	End Function
	Function CompilerManifestFileRecordMalformed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_FILE_RECORD_MALFORMED, "BMKGEN002 malformed compiler build file record")
	End Function
	Function CompilerManifestUnsafeFilePath:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_UNSAFE_FILE_PATH, "BMKGEN003 unsafe compiler build file path")
	End Function
	Function CompilerManifestDuplicateFilePath:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_DUPLICATE_FILE_PATH, "BMKGEN004 duplicate compiler build file path")
	End Function
	Function CompilerManifestLinkIdentityMalformed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_LINK_IDENTITY_MALFORMED, "BMKGEN005 malformed compiler build link identity")
	End Function
	Function CompilerManifestUnsafeLinkPath:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_UNSAFE_LINK_PATH, "BMKGEN006 unsafe compiler build link path")
	End Function
	Function CompilerManifestDuplicateLinkInput:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_DUPLICATE_LINK_INPUT, "BMKGEN007 duplicate compiler build link input")
	End Function
	Function CompilerManifestRecordMalformed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_RECORD_MALFORMED, "BMKGEN008 unknown or malformed compiler build manifest record")
	End Function
	Function CompilerManifestMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_MISSING, "BMKGEN009 compiler build manifest is missing: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CompilerManifestEncodedFieldMalformed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_ENCODED_FIELD_MALFORMED, "BMKGEN010 malformed encoded compiler build manifest field")
	End Function
	Function CompilerManifestUnsafePathResolution:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_MANIFEST_UNSAFE_PATH_RESOLUTION, "BMKGEN011 refusing to resolve unsafe compiler build path")
	End Function
	Function CompilerOutputHashFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_COMPILER_OUTPUT_HASH_FAILED, "BMKGEN025 declared compiler output cannot be hashed: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CleanGeneratedFileRemovalFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_GENERATED_FILE_REMOVAL_FAILED, "BMKCLEAN006 unable to remove generated file: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CleanGeneratedDirectoryRemovalFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_GENERATED_DIRECTORY_REMOVAL_FAILED, "BMKCLEAN007 unable to remove generated directory: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CleanSymbolicOutputFileRefused:TLocalisedMessage(cache_kind:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_SYMBOLIC_OUTPUT_FILE_REFUSED, "BMKCLEAN002 refusing symbolic {cache_kind} output file: {path}", [TMessageArg.Create("cache_kind", cache_kind), TMessageArg.Create("path", path)])
	End Function
	Function CleanCacheEntryOutsideDirectory:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_CACHE_ENTRY_OUTSIDE_DIRECTORY, "BMKCLEAN004 refusing cache entry outside the selected directory: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CleanUnexpectedCacheDirectory:TLocalisedMessage(expected_leaf:String, cache_kind:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_UNEXPECTED_CACHE_DIRECTORY, "BMKCLEAN001 refusing non-{expected_leaf} {cache_kind} cache directory: {path}", [TMessageArg.Create("expected_leaf", expected_leaf), TMessageArg.Create("cache_kind", cache_kind), TMessageArg.Create("path", path)])
	End Function
	Function CleanSymbolicCacheDirectoryRefused:TLocalisedMessage(cache_kind:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_SYMBOLIC_CACHE_DIRECTORY_REFUSED, "BMKCLEAN002 refusing symbolic {cache_kind} cache directory: {path}", [TMessageArg.Create("cache_kind", cache_kind), TMessageArg.Create("path", path)])
	End Function
	Function CleanCachePathNotDirectory:TLocalisedMessage(cache_kind:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_CACHE_PATH_NOT_DIRECTORY, "BMKCLEAN003 {cache_kind} cache path is not a directory: {path}", [TMessageArg.Create("cache_kind", cache_kind), TMessageArg.Create("path", path)])
	End Function
	Function CleanSymbolicLinkInsideCacheRefused:TLocalisedMessage(cache_kind:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_SYMBOLIC_LINK_INSIDE_CACHE_REFUSED, "BMKCLEAN002 refusing symbolic link inside {cache_kind} cache: {path}", [TMessageArg.Create("cache_kind", cache_kind), TMessageArg.Create("path", path)])
	End Function
	Function CleanUnsupportedCacheEntry:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_UNSUPPORTED_CACHE_ENTRY, "BMKCLEAN005 refusing unsupported cache entry: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function CleanUnsupportedOutput:TLocalisedMessage(cache_kind:String, path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CLEAN_UNSUPPORTED_OUTPUT, "BMKCLEAN005 refusing unsupported {cache_kind} output: {path}", [TMessageArg.Create("cache_kind", cache_kind), TMessageArg.Create("path", path)])
	End Function
	Function Bcc2EngineStartFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_START_FAILED, "BMKGEN043 unable to start bcc engine: {path}", [TMessageArg.Create("path", path)])
	End Function
	Function Bcc2EngineHandshakeIncompatible:TLocalisedMessage(expected:String, received:String, detail:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_HANDSHAKE_INCOMPATIBLE, "BMKGEN044 incompatible bcc engine handshake: expected '{expected}', received '{received}'{detail}", [TMessageArg.Create("expected", expected), TMessageArg.Create("received", received), TMessageArg.Create("detail", detail)])
	End Function
	Function Bcc2EngineNotRunning:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_NOT_RUNNING, "BMKGEN045 bcc engine is not running")
	End Function
	Function Bcc2EngineResultHeaderMalformed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_RESULT_HEADER_MALFORMED, "BMKGEN046 malformed bcc2 engine result header")
	End Function
	Function Bcc2EngineResultLengthMalformed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_RESULT_LENGTH_MALFORMED, "BMKGEN046 malformed bcc2 engine result length")
	End Function
	Function Bcc2EngineResultBodyMalformed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_RESULT_BODY_MALFORMED, "BMKGEN046 malformed bcc2 engine result body")
	End Function
	Function Bcc2EngineResultBodyIncomplete:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_RESULT_BODY_INCOMPLETE, "BMKGEN046 incomplete bcc2 engine result body")
	End Function
	Function Bcc2EngineCacheInvalidationNotRunning:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_CACHE_INVALIDATION_NOT_RUNNING, "BMKGEN045 bcc2 engine is not running")
	End Function
	Function Bcc2EngineCacheInvalidationRejected:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_CACHE_INVALIDATION_REJECTED, "BMKGEN048 bcc2 engine rejected cache invalidation")
	End Function
	Function Bcc2EngineExitedUnexpectedly:TLocalisedMessage(detail:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BCC2_ENGINE_EXITED_UNEXPECTEDLY, "BMKGEN047 bcc engine exited unexpectedly{detail}", [TMessageArg.Create("detail", detail)])
	End Function
	Function ConfigRequiredLoadFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CONFIG_REQUIRED_LOAD_FAILED, "Could not load required config '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function ToolchainGccProcessNotFound:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TOOLCHAIN_GCC_PROCESS_NOT_FOUND, "Cannot find a valid GCC compiler. Please check your paths and environment.")
	End Function
	Function ToolchainXcodebuildNotFound:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TOOLCHAIN_XCODEBUILD_NOT_FOUND, "Cannot find xcodebuild. Please check your paths and environment.")
	End Function
	Function MingwDllCrtPathMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_MINGW_DLL_CRT_PATH_MISSING, "Could not determine MinGWDLLCrtPath : Expecting '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function MingwCrtPathMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_MINGW_CRT_PATH_MISSING, "Could not determine MinGWCrtPath: Expecting '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function MingwCrtPathsMissing:TLocalisedMessage(first_path:String, second_path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_MINGW_CRT_PATHS_MISSING, "Could not determine MinGWCrtPath: Expecting '{first_path}' or '{second_path}'", [TMessageArg.Create("first_path", first_path), TMessageArg.Create("second_path", second_path)])
	End Function
	Function BuildOutputPublishFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_BUILD_OUTPUT_PUBLISH_FAILED, "Build Error: failed to publish {path}", [TMessageArg.Create("path", path)])
	End Function
	Function OptionsExpressionClosingParenthesisExpected:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTIONS_EXPRESSION_CLOSING_PARENTHESIS_EXPECTED, "Expected ')'")
	End Function
	Function OptionsExpressionClosingParenthesisUnexpected:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTIONS_EXPRESSION_CLOSING_PARENTHESIS_UNEXPECTED, "Unexpected ')'")
	End Function
	Function OptionsExpressionCharacterUnexpected:TLocalisedMessage(character:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTIONS_EXPRESSION_CHARACTER_UNEXPECTED, "Unexpected character : {character}", [TMessageArg.Create("character", character)])
	End Function
	Function OptionsExpressionMissing:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTIONS_EXPRESSION_MISSING, "Missing expression")
	End Function
	Function ModuleArchiveInterfaceMissing:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_MODULE_ARCHIVE_INTERFACE_MISSING, "Failed to find module interface '{path}'", [TMessageArg.Create("path", path)])
	End Function
	Function ModuleArchivePublishFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_MODULE_ARCHIVE_PUBLISH_FAILED, "Failed to publish module")
	End Function
	Function ModuleArchiveDirectoryCreationFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_MODULE_ARCHIVE_DIRECTORY_CREATION_FAILED, "Unable to create module directory")
	End Function
	Function ConversionFilenameRequired:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CONVERSION_FILENAME_REQUIRED, "convertbb option requires a filename")
	End Function
	Function ConversionSourceOpenFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CONVERSION_SOURCE_OPEN_FAILED, "bb2bmx failed to open {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ConversionIncludedSourceOpenFailed:TLocalisedMessage(path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_CONVERSION_INCLUDED_SOURCE_OPEN_FAILED, "bb2bmx failed to open included file {path}", [TMessageArg.Create("path", path)])
	End Function
	Function ModuleAmbiguous:TLocalisedMessage(name:String, first_path:String, second_path:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_MODULE_AMBIGUOUS, "Ambiguous module '{name}' maps to both '{first_path}' and '{second_path}'", [TMessageArg.Create("name", name), TMessageArg.Create("first_path", first_path), TMessageArg.Create("second_path", second_path)])
	End Function
	Function TargetPlatformArchitectureInvalid:TLocalisedMessage(platform:String, architecture:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_TARGET_PLATFORM_ARCHITECTURE_INVALID, "Invalid Platform/Architecture configuration : {platform}/{architecture}", [TMessageArg.Create("platform", platform), TMessageArg.Create("architecture", architecture)])
	End Function
	Function OptionHeapRegionRequiresPico:TLocalisedMessage()
		Return TLocalisedMessage.Create("bmk", BMK_MSG_OPTION_HEAP_REGION_REQUIRES_PICO, "-heap-region is currently supported only by the pico target")
	End Function
	Function PicoHeapRegionInvalid:TLocalisedMessage(value:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_HEAP_REGION_INVALID, "Invalid Pico heap region '{value}'; expected 'sram' or 'psram'", [TMessageArg.Create("value", value)])
	End Function
	Function PicoHeapPsramFixedSizeRequired:TLocalisedMessage(board:String)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_HEAP_PSRAM_FIXED_SIZE_REQUIRED, "Pico SDK board '{board}' does not define a fixed PSRAM size required for a PSRAM managed heap", [TMessageArg.Create("board", board)])
	End Function
	Function PicoHeapPsramCapacityExceeded:TLocalisedMessage(heap_bytes:Long, psram_bytes:Long)
		Return TLocalisedMessage.Create("bmk", BMK_MSG_PICO_HEAP_PSRAM_CAPACITY_EXCEEDED, "Pico managed heap size {heap_bytes} exceeds the board PSRAM capacity of {psram_bytes} bytes", [TMessageArg.CreateInt("heap_bytes", heap_bytes), TMessageArg.CreateInt("psram_bytes", psram_bytes)])
	End Function
End Type
